// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpcpb/key.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateToNodeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateToNodeIdRequest) Reset() {
	*x = CertificateToNodeIdRequest{}
	mi := &file_rpcpb_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateToNodeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateToNodeIdRequest) ProtoMessage() {}

func (x *CertificateToNodeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateToNodeIdRequest.ProtoReflect.Descriptor instead.
func (*CertificateToNodeIdRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateToNodeIdRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertificateToNodeIdRequest) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type CertificateToNodeIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedNodeId []byte                 `protobuf:"bytes,1,opt,name=expected_node_id,json=expectedNodeId,proto3" json:"expected_node_id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertificateToNodeIdResponse) Reset() {
	*x = CertificateToNodeIdResponse{}
	mi := &file_rpcpb_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateToNodeIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateToNodeIdResponse) ProtoMessage() {}

func (x *CertificateToNodeIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateToNodeIdResponse.ProtoReflect.Descriptor instead.
func (*CertificateToNodeIdResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateToNodeIdResponse) GetExpectedNodeId() []byte {
	if x != nil {
		return x.ExpectedNodeId
	}
	return nil
}

func (x *CertificateToNodeIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CertificateToNodeIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Secp256K1RecoverHashPublicKeyRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Message              []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKeyShortIdCb58 string                 `protobuf:"bytes,3,opt,name=public_key_short_id_cb58,json=publicKeyShortIdCb58,proto3" json:"public_key_short_id_cb58,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Secp256K1RecoverHashPublicKeyRequest) Reset() {
	*x = Secp256K1RecoverHashPublicKeyRequest{}
	mi := &file_rpcpb_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secp256K1RecoverHashPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secp256K1RecoverHashPublicKeyRequest) ProtoMessage() {}

func (x *Secp256K1RecoverHashPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secp256K1RecoverHashPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*Secp256K1RecoverHashPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{2}
}

func (x *Secp256K1RecoverHashPublicKeyRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Secp256K1RecoverHashPublicKeyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Secp256K1RecoverHashPublicKeyRequest) GetPublicKeyShortIdCb58() string {
	if x != nil {
		return x.PublicKeyShortIdCb58
	}
	return ""
}

type Secp256K1RecoverHashPublicKeyResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ExpectedPublicKeyShortIdCb58 string                 `protobuf:"bytes,1,opt,name=expected_public_key_short_id_cb58,json=expectedPublicKeyShortIdCb58,proto3" json:"expected_public_key_short_id_cb58,omitempty"`
	Message                      string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success                      bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Secp256K1RecoverHashPublicKeyResponse) Reset() {
	*x = Secp256K1RecoverHashPublicKeyResponse{}
	mi := &file_rpcpb_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secp256K1RecoverHashPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secp256K1RecoverHashPublicKeyResponse) ProtoMessage() {}

func (x *Secp256K1RecoverHashPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secp256K1RecoverHashPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*Secp256K1RecoverHashPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{3}
}

func (x *Secp256K1RecoverHashPublicKeyResponse) GetExpectedPublicKeyShortIdCb58() string {
	if x != nil {
		return x.ExpectedPublicKeyShortIdCb58
	}
	return ""
}

func (x *Secp256K1RecoverHashPublicKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Secp256K1RecoverHashPublicKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Secp256K1InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secp256K1Info *Secp256K1Info         `protobuf:"bytes,1,opt,name=secp256k1_info,json=secp256k1Info,proto3" json:"secp256k1_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secp256K1InfoRequest) Reset() {
	*x = Secp256K1InfoRequest{}
	mi := &file_rpcpb_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secp256K1InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secp256K1InfoRequest) ProtoMessage() {}

func (x *Secp256K1InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secp256K1InfoRequest.ProtoReflect.Descriptor instead.
func (*Secp256K1InfoRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{4}
}

func (x *Secp256K1InfoRequest) GetSecp256K1Info() *Secp256K1Info {
	if x != nil {
		return x.Secp256K1Info
	}
	return nil
}

type Secp256K1InfoResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ExpectedSecp256K1Info *Secp256K1Info         `protobuf:"bytes,1,opt,name=expected_secp256k1_info,json=expectedSecp256k1Info,proto3" json:"expected_secp256k1_info,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success               bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Secp256K1InfoResponse) Reset() {
	*x = Secp256K1InfoResponse{}
	mi := &file_rpcpb_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secp256K1InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secp256K1InfoResponse) ProtoMessage() {}

func (x *Secp256K1InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secp256K1InfoResponse.ProtoReflect.Descriptor instead.
func (*Secp256K1InfoResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{5}
}

func (x *Secp256K1InfoResponse) GetExpectedSecp256K1Info() *Secp256K1Info {
	if x != nil {
		return x.ExpectedSecp256K1Info
	}
	return nil
}

func (x *Secp256K1InfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Secp256K1InfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Secp256K1Info struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyType        string                 `protobuf:"bytes,1,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	PrivateKeyCb58 string                 `protobuf:"bytes,2,opt,name=private_key_cb58,json=privateKeyCb58,proto3" json:"private_key_cb58,omitempty"`
	PrivateKeyHex  string                 `protobuf:"bytes,3,opt,name=private_key_hex,json=privateKeyHex,proto3" json:"private_key_hex,omitempty"`
	// Map from network ID to its chain addresses.
	ChainAddresses map[uint32]*ChainAddresses `protobuf:"bytes,4,rep,name=chain_addresses,json=chainAddresses,proto3" json:"chain_addresses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShortAddress   string                     `protobuf:"bytes,5,opt,name=short_address,json=shortAddress,proto3" json:"short_address,omitempty"`
	EthAddress     string                     `protobuf:"bytes,6,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Secp256K1Info) Reset() {
	*x = Secp256K1Info{}
	mi := &file_rpcpb_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secp256K1Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secp256K1Info) ProtoMessage() {}

func (x *Secp256K1Info) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secp256K1Info.ProtoReflect.Descriptor instead.
func (*Secp256K1Info) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{6}
}

func (x *Secp256K1Info) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *Secp256K1Info) GetPrivateKeyCb58() string {
	if x != nil {
		return x.PrivateKeyCb58
	}
	return ""
}

func (x *Secp256K1Info) GetPrivateKeyHex() string {
	if x != nil {
		return x.PrivateKeyHex
	}
	return ""
}

func (x *Secp256K1Info) GetChainAddresses() map[uint32]*ChainAddresses {
	if x != nil {
		return x.ChainAddresses
	}
	return nil
}

func (x *Secp256K1Info) GetShortAddress() string {
	if x != nil {
		return x.ShortAddress
	}
	return ""
}

func (x *Secp256K1Info) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

type ChainAddresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             string                 `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	P             string                 `protobuf:"bytes,2,opt,name=p,proto3" json:"p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainAddresses) Reset() {
	*x = ChainAddresses{}
	mi := &file_rpcpb_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainAddresses) ProtoMessage() {}

func (x *ChainAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainAddresses.ProtoReflect.Descriptor instead.
func (*ChainAddresses) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{7}
}

func (x *ChainAddresses) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *ChainAddresses) GetP() string {
	if x != nil {
		return x.P
	}
	return ""
}

type BlsSignatureRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey                 []byte                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey                  []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Message                    []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Signature                  []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureProofOfPossession []byte                 `protobuf:"bytes,5,opt,name=signature_proof_of_possession,json=signatureProofOfPossession,proto3" json:"signature_proof_of_possession,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BlsSignatureRequest) Reset() {
	*x = BlsSignatureRequest{}
	mi := &file_rpcpb_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlsSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlsSignatureRequest) ProtoMessage() {}

func (x *BlsSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlsSignatureRequest.ProtoReflect.Descriptor instead.
func (*BlsSignatureRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{8}
}

func (x *BlsSignatureRequest) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *BlsSignatureRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *BlsSignatureRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BlsSignatureRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlsSignatureRequest) GetSignatureProofOfPossession() []byte {
	if x != nil {
		return x.SignatureProofOfPossession
	}
	return nil
}

type BlsSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlsSignatureResponse) Reset() {
	*x = BlsSignatureResponse{}
	mi := &file_rpcpb_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlsSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlsSignatureResponse) ProtoMessage() {}

func (x *BlsSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlsSignatureResponse.ProtoReflect.Descriptor instead.
func (*BlsSignatureResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_key_proto_rawDescGZIP(), []int{9}
}

func (x *BlsSignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlsSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpcpb_key_proto protoreflect.FileDescriptor

const file_rpcpb_key_proto_rawDesc = "" +
	"\n" +
	"\x0frpcpb/key.proto\x12\x05rpcpb\"W\n" +
	"\x1aCertificateToNodeIdRequest\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\"{\n" +
	"\x1bCertificateToNodeIdResponse\x12(\n" +
	"\x10expected_node_id\x18\x01 \x01(\fR\x0eexpectedNodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x96\x01\n" +
	"$Secp256k1RecoverHashPublicKeyRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x126\n" +
	"\x18public_key_short_id_cb58\x18\x03 \x01(\tR\x14publicKeyShortIdCb58\"\xa4\x01\n" +
	"%Secp256k1RecoverHashPublicKeyResponse\x12G\n" +
	"!expected_public_key_short_id_cb58\x18\x01 \x01(\tR\x1cexpectedPublicKeyShortIdCb58\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"S\n" +
	"\x14Secp256k1InfoRequest\x12;\n" +
	"\x0esecp256k1_info\x18\x01 \x01(\v2\x14.rpcpb.Secp256k1InfoR\rsecp256k1Info\"\x99\x01\n" +
	"\x15Secp256k1InfoResponse\x12L\n" +
	"\x17expected_secp256k1_info\x18\x01 \x01(\v2\x14.rpcpb.Secp256k1InfoR\x15expectedSecp256k1Info\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xef\x02\n" +
	"\rSecp256k1Info\x12\x19\n" +
	"\bkey_type\x18\x01 \x01(\tR\akeyType\x12(\n" +
	"\x10private_key_cb58\x18\x02 \x01(\tR\x0eprivateKeyCb58\x12&\n" +
	"\x0fprivate_key_hex\x18\x03 \x01(\tR\rprivateKeyHex\x12Q\n" +
	"\x0fchain_addresses\x18\x04 \x03(\v2(.rpcpb.Secp256k1Info.ChainAddressesEntryR\x0echainAddresses\x12#\n" +
	"\rshort_address\x18\x05 \x01(\tR\fshortAddress\x12\x1f\n" +
	"\veth_address\x18\x06 \x01(\tR\n" +
	"ethAddress\x1aX\n" +
	"\x13ChainAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.rpcpb.ChainAddressesR\x05value:\x028\x01\",\n" +
	"\x0eChainAddresses\x12\f\n" +
	"\x01x\x18\x01 \x01(\tR\x01x\x12\f\n" +
	"\x01p\x18\x02 \x01(\tR\x01p\"\xd0\x01\n" +
	"\x13BlsSignatureRequest\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12A\n" +
	"\x1dsignature_proof_of_possession\x18\x05 \x01(\fR\x1asignatureProofOfPossession\"J\n" +
	"\x14BlsSignatureResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x83\x03\n" +
	"\n" +
	"KeyService\x12^\n" +
	"\x13CertificateToNodeId\x12!.rpcpb.CertificateToNodeIdRequest\x1a\".rpcpb.CertificateToNodeIdResponse\"\x00\x12|\n" +
	"\x1dSecp256k1RecoverHashPublicKey\x12+.rpcpb.Secp256k1RecoverHashPublicKeyRequest\x1a,.rpcpb.Secp256k1RecoverHashPublicKeyResponse\"\x00\x12L\n" +
	"\rSecp256k1Info\x12\x1b.rpcpb.Secp256k1InfoRequest\x1a\x1c.rpcpb.Secp256k1InfoResponse\"\x00\x12I\n" +
	"\fBlsSignature\x12\x1a.rpcpb.BlsSignatureRequest\x1a\x1b.rpcpb.BlsSignatureResponse\"\x00B@Z>github.com/ava-labs/avalanche-rs/avalanchego-conformance;rpcpbb\x06proto3"

var (
	file_rpcpb_key_proto_rawDescOnce sync.Once
	file_rpcpb_key_proto_rawDescData []byte
)

func file_rpcpb_key_proto_rawDescGZIP() []byte {
	file_rpcpb_key_proto_rawDescOnce.Do(func() {
		file_rpcpb_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_key_proto_rawDesc), len(file_rpcpb_key_proto_rawDesc)))
	})
	return file_rpcpb_key_proto_rawDescData
}

var file_rpcpb_key_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpcpb_key_proto_goTypes = []any{
	(*CertificateToNodeIdRequest)(nil),            // 0: rpcpb.CertificateToNodeIdRequest
	(*CertificateToNodeIdResponse)(nil),           // 1: rpcpb.CertificateToNodeIdResponse
	(*Secp256K1RecoverHashPublicKeyRequest)(nil),  // 2: rpcpb.Secp256k1RecoverHashPublicKeyRequest
	(*Secp256K1RecoverHashPublicKeyResponse)(nil), // 3: rpcpb.Secp256k1RecoverHashPublicKeyResponse
	(*Secp256K1InfoRequest)(nil),                  // 4: rpcpb.Secp256k1InfoRequest
	(*Secp256K1InfoResponse)(nil),                 // 5: rpcpb.Secp256k1InfoResponse
	(*Secp256K1Info)(nil),                         // 6: rpcpb.Secp256k1Info
	(*ChainAddresses)(nil),                        // 7: rpcpb.ChainAddresses
	(*BlsSignatureRequest)(nil),                   // 8: rpcpb.BlsSignatureRequest
	(*BlsSignatureResponse)(nil),                  // 9: rpcpb.BlsSignatureResponse
	nil,                                           // 10: rpcpb.Secp256k1Info.ChainAddressesEntry
}
var file_rpcpb_key_proto_depIdxs = []int32{
	6,  // 0: rpcpb.Secp256k1InfoRequest.secp256k1_info:type_name -> rpcpb.Secp256k1Info
	6,  // 1: rpcpb.Secp256k1InfoResponse.expected_secp256k1_info:type_name -> rpcpb.Secp256k1Info
	10, // 2: rpcpb.Secp256k1Info.chain_addresses:type_name -> rpcpb.Secp256k1Info.ChainAddressesEntry
	7,  // 3: rpcpb.Secp256k1Info.ChainAddressesEntry.value:type_name -> rpcpb.ChainAddresses
	0,  // 4: rpcpb.KeyService.CertificateToNodeId:input_type -> rpcpb.CertificateToNodeIdRequest
	2,  // 5: rpcpb.KeyService.Secp256k1RecoverHashPublicKey:input_type -> rpcpb.Secp256k1RecoverHashPublicKeyRequest
	4,  // 6: rpcpb.KeyService.Secp256k1Info:input_type -> rpcpb.Secp256k1InfoRequest
	8,  // 7: rpcpb.KeyService.BlsSignature:input_type -> rpcpb.BlsSignatureRequest
	1,  // 8: rpcpb.KeyService.CertificateToNodeId:output_type -> rpcpb.CertificateToNodeIdResponse
	3,  // 9: rpcpb.KeyService.Secp256k1RecoverHashPublicKey:output_type -> rpcpb.Secp256k1RecoverHashPublicKeyResponse
	5,  // 10: rpcpb.KeyService.Secp256k1Info:output_type -> rpcpb.Secp256k1InfoResponse
	9,  // 11: rpcpb.KeyService.BlsSignature:output_type -> rpcpb.BlsSignatureResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpcpb_key_proto_init() }
func file_rpcpb_key_proto_init() {
	if File_rpcpb_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_key_proto_rawDesc), len(file_rpcpb_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_key_proto_goTypes,
		DependencyIndexes: file_rpcpb_key_proto_depIdxs,
		MessageInfos:      file_rpcpb_key_proto_msgTypes,
	}.Build()
	File_rpcpb_key_proto = out.File
	file_rpcpb_key_proto_goTypes = nil
	file_rpcpb_key_proto_depIdxs = nil
}
