// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpcpb/l1tx.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertSubnetToL1TxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertSubnetToL1TxResponse) Reset() {
	*x = ConvertSubnetToL1TxResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertSubnetToL1TxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertSubnetToL1TxResponse) ProtoMessage() {}

func (x *ConvertSubnetToL1TxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertSubnetToL1TxResponse.ProtoReflect.Descriptor instead.
func (*ConvertSubnetToL1TxResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertSubnetToL1TxResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *ConvertSubnetToL1TxResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *ConvertSubnetToL1TxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConvertSubnetToL1TxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterL1ValidatorTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterL1ValidatorTxResponse) Reset() {
	*x = RegisterL1ValidatorTxResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterL1ValidatorTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterL1ValidatorTxResponse) ProtoMessage() {}

func (x *RegisterL1ValidatorTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterL1ValidatorTxResponse.ProtoReflect.Descriptor instead.
func (*RegisterL1ValidatorTxResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterL1ValidatorTxResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *RegisterL1ValidatorTxResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *RegisterL1ValidatorTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterL1ValidatorTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetL1ValidatorWeightTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetL1ValidatorWeightTxResponse) Reset() {
	*x = SetL1ValidatorWeightTxResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetL1ValidatorWeightTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetL1ValidatorWeightTxResponse) ProtoMessage() {}

func (x *SetL1ValidatorWeightTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetL1ValidatorWeightTxResponse.ProtoReflect.Descriptor instead.
func (*SetL1ValidatorWeightTxResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{2}
}

func (x *SetL1ValidatorWeightTxResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *SetL1ValidatorWeightTxResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *SetL1ValidatorWeightTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetL1ValidatorWeightTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncreaseL1ValidatorBalanceTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseL1ValidatorBalanceTxResponse) Reset() {
	*x = IncreaseL1ValidatorBalanceTxResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseL1ValidatorBalanceTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseL1ValidatorBalanceTxResponse) ProtoMessage() {}

func (x *IncreaseL1ValidatorBalanceTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseL1ValidatorBalanceTxResponse.ProtoReflect.Descriptor instead.
func (*IncreaseL1ValidatorBalanceTxResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{3}
}

func (x *IncreaseL1ValidatorBalanceTxResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IncreaseL1ValidatorBalanceTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisableL1ValidatorTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableL1ValidatorTxResponse) Reset() {
	*x = DisableL1ValidatorTxResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableL1ValidatorTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableL1ValidatorTxResponse) ProtoMessage() {}

func (x *DisableL1ValidatorTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableL1ValidatorTxResponse.ProtoReflect.Descriptor instead.
func (*DisableL1ValidatorTxResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{4}
}

func (x *DisableL1ValidatorTxResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *DisableL1ValidatorTxResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *DisableL1ValidatorTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DisableL1ValidatorTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WarpUnsignedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpUnsignedMessageResponse) Reset() {
	*x = WarpUnsignedMessageResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpUnsignedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpUnsignedMessageResponse) ProtoMessage() {}

func (x *WarpUnsignedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpUnsignedMessageResponse.ProtoReflect.Descriptor instead.
func (*WarpUnsignedMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{5}
}

func (x *WarpUnsignedMessageResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *WarpUnsignedMessageResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *WarpUnsignedMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WarpUnsignedMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WarpMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpMessageResponse) Reset() {
	*x = WarpMessageResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpMessageResponse) ProtoMessage() {}

func (x *WarpMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpMessageResponse.ProtoReflect.Descriptor instead.
func (*WarpMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{6}
}

func (x *WarpMessageResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *WarpMessageResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *WarpMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WarpMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterL1ValidatorPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterL1ValidatorPayloadResponse) Reset() {
	*x = RegisterL1ValidatorPayloadResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterL1ValidatorPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterL1ValidatorPayloadResponse) ProtoMessage() {}

func (x *RegisterL1ValidatorPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterL1ValidatorPayloadResponse.ProtoReflect.Descriptor instead.
func (*RegisterL1ValidatorPayloadResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterL1ValidatorPayloadResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterL1ValidatorPayloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type L1ValidatorWeightPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1ValidatorWeightPayloadResponse) Reset() {
	*x = L1ValidatorWeightPayloadResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1ValidatorWeightPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1ValidatorWeightPayloadResponse) ProtoMessage() {}

func (x *L1ValidatorWeightPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1ValidatorWeightPayloadResponse.ProtoReflect.Descriptor instead.
func (*L1ValidatorWeightPayloadResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{8}
}

func (x *L1ValidatorWeightPayloadResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *L1ValidatorWeightPayloadResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *L1ValidatorWeightPayloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *L1ValidatorWeightPayloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubnetToL1ConversionPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	ComputedId    []byte                 `protobuf:"bytes,2,opt,name=computed_id,json=computedId,proto3" json:"computed_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetToL1ConversionPayloadResponse) Reset() {
	*x = SubnetToL1ConversionPayloadResponse{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetToL1ConversionPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetToL1ConversionPayloadResponse) ProtoMessage() {}

func (x *SubnetToL1ConversionPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetToL1ConversionPayloadResponse.ProtoReflect.Descriptor instead.
func (*SubnetToL1ConversionPayloadResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{9}
}

func (x *SubnetToL1ConversionPayloadResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *SubnetToL1ConversionPayloadResponse) GetComputedId() []byte {
	if x != nil {
		return x.ComputedId
	}
	return nil
}

func (x *SubnetToL1ConversionPayloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubnetToL1ConversionPayloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ConvertSubnetToL1Tx converts a permissioned Subnet to an L1 (Type ID: 32)
type ConvertSubnetToL1TxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base transaction fields
	NetworkId    uint32                `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BlockchainId []byte                `protobuf:"bytes,2,opt,name=blockchain_id,json=blockchainId,proto3" json:"blockchain_id,omitempty"`
	Outputs      []*TransferableOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs       []*TransferableInput  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Memo         []byte                `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// ConvertSubnetToL1Tx specific fields
	SubnetId   []byte                `protobuf:"bytes,6,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	ChainId    []byte                `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address    []byte                `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"` // Subnet manager address
	Validators []*InitialL1Validator `protobuf:"bytes,9,rep,name=validators,proto3" json:"validators,omitempty"`
	SubnetAuth []byte                `protobuf:"bytes,10,opt,name=subnet_auth,json=subnetAuth,proto3" json:"subnet_auth,omitempty"` // Subnet authorization credentials
	// Rust-serialized bytes for comparison
	SerializedTx  []byte `protobuf:"bytes,11,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertSubnetToL1TxRequest) Reset() {
	*x = ConvertSubnetToL1TxRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertSubnetToL1TxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertSubnetToL1TxRequest) ProtoMessage() {}

func (x *ConvertSubnetToL1TxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertSubnetToL1TxRequest.ProtoReflect.Descriptor instead.
func (*ConvertSubnetToL1TxRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{10}
}

func (x *ConvertSubnetToL1TxRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *ConvertSubnetToL1TxRequest) GetBlockchainId() []byte {
	if x != nil {
		return x.BlockchainId
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetOutputs() []*TransferableOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetInputs() []*TransferableInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetSubnetId() []byte {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetValidators() []*InitialL1Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetSubnetAuth() []byte {
	if x != nil {
		return x.SubnetAuth
	}
	return nil
}

func (x *ConvertSubnetToL1TxRequest) GetSerializedTx() []byte {
	if x != nil {
		return x.SerializedTx
	}
	return nil
}

// RegisterL1ValidatorTx registers a new L1 validator via Warp message (Type ID: 33)
type RegisterL1ValidatorTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base transaction fields
	NetworkId    uint32                `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BlockchainId []byte                `protobuf:"bytes,2,opt,name=blockchain_id,json=blockchainId,proto3" json:"blockchain_id,omitempty"`
	Outputs      []*TransferableOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs       []*TransferableInput  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Memo         []byte                `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// RegisterL1ValidatorTx specific fields
	Balance              uint64            `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	BlsProofOfPossession []byte            `protobuf:"bytes,7,opt,name=bls_proof_of_possession,json=blsProofOfPossession,proto3" json:"bls_proof_of_possession,omitempty"` // 96 bytes
	WarpMessage          *WarpMessageBytes `protobuf:"bytes,8,opt,name=warp_message,json=warpMessage,proto3" json:"warp_message,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedTx  []byte `protobuf:"bytes,9,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterL1ValidatorTxRequest) Reset() {
	*x = RegisterL1ValidatorTxRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterL1ValidatorTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterL1ValidatorTxRequest) ProtoMessage() {}

func (x *RegisterL1ValidatorTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterL1ValidatorTxRequest.ProtoReflect.Descriptor instead.
func (*RegisterL1ValidatorTxRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterL1ValidatorTxRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *RegisterL1ValidatorTxRequest) GetBlockchainId() []byte {
	if x != nil {
		return x.BlockchainId
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetOutputs() []*TransferableOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetInputs() []*TransferableInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *RegisterL1ValidatorTxRequest) GetBlsProofOfPossession() []byte {
	if x != nil {
		return x.BlsProofOfPossession
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetWarpMessage() *WarpMessageBytes {
	if x != nil {
		return x.WarpMessage
	}
	return nil
}

func (x *RegisterL1ValidatorTxRequest) GetSerializedTx() []byte {
	if x != nil {
		return x.SerializedTx
	}
	return nil
}

// SetL1ValidatorWeightTx updates validator weight via Warp message (Type ID: 34)
type SetL1ValidatorWeightTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base transaction fields
	NetworkId    uint32                `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BlockchainId []byte                `protobuf:"bytes,2,opt,name=blockchain_id,json=blockchainId,proto3" json:"blockchain_id,omitempty"`
	Outputs      []*TransferableOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs       []*TransferableInput  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Memo         []byte                `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// SetL1ValidatorWeightTx specific fields
	WarpMessage *WarpMessageBytes `protobuf:"bytes,6,opt,name=warp_message,json=warpMessage,proto3" json:"warp_message,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedTx  []byte `protobuf:"bytes,7,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetL1ValidatorWeightTxRequest) Reset() {
	*x = SetL1ValidatorWeightTxRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetL1ValidatorWeightTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetL1ValidatorWeightTxRequest) ProtoMessage() {}

func (x *SetL1ValidatorWeightTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetL1ValidatorWeightTxRequest.ProtoReflect.Descriptor instead.
func (*SetL1ValidatorWeightTxRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{12}
}

func (x *SetL1ValidatorWeightTxRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *SetL1ValidatorWeightTxRequest) GetBlockchainId() []byte {
	if x != nil {
		return x.BlockchainId
	}
	return nil
}

func (x *SetL1ValidatorWeightTxRequest) GetOutputs() []*TransferableOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *SetL1ValidatorWeightTxRequest) GetInputs() []*TransferableInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *SetL1ValidatorWeightTxRequest) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *SetL1ValidatorWeightTxRequest) GetWarpMessage() *WarpMessageBytes {
	if x != nil {
		return x.WarpMessage
	}
	return nil
}

func (x *SetL1ValidatorWeightTxRequest) GetSerializedTx() []byte {
	if x != nil {
		return x.SerializedTx
	}
	return nil
}

// IncreaseL1ValidatorBalanceTx adds to a validator's balance (Type ID: 36)
type IncreaseL1ValidatorBalanceTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base transaction fields
	NetworkId    uint32                `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BlockchainId []byte                `protobuf:"bytes,2,opt,name=blockchain_id,json=blockchainId,proto3" json:"blockchain_id,omitempty"`
	Outputs      []*TransferableOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs       []*TransferableInput  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Memo         []byte                `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// IncreaseL1ValidatorBalanceTx specific fields
	ValidationId []byte `protobuf:"bytes,6,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"` // 32 bytes
	Balance      uint64 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedTx  []byte `protobuf:"bytes,8,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseL1ValidatorBalanceTxRequest) Reset() {
	*x = IncreaseL1ValidatorBalanceTxRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseL1ValidatorBalanceTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseL1ValidatorBalanceTxRequest) ProtoMessage() {}

func (x *IncreaseL1ValidatorBalanceTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseL1ValidatorBalanceTxRequest.ProtoReflect.Descriptor instead.
func (*IncreaseL1ValidatorBalanceTxRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{13}
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetBlockchainId() []byte {
	if x != nil {
		return x.BlockchainId
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetOutputs() []*TransferableOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetInputs() []*TransferableInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetValidationId() []byte {
	if x != nil {
		return x.ValidationId
	}
	return nil
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *IncreaseL1ValidatorBalanceTxRequest) GetSerializedTx() []byte {
	if x != nil {
		return x.SerializedTx
	}
	return nil
}

// DisableL1ValidatorTx deactivates a validator (Type ID: 35)
type DisableL1ValidatorTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base transaction fields
	NetworkId    uint32                `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BlockchainId []byte                `protobuf:"bytes,2,opt,name=blockchain_id,json=blockchainId,proto3" json:"blockchain_id,omitempty"`
	Outputs      []*TransferableOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Inputs       []*TransferableInput  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Memo         []byte                `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// DisableL1ValidatorTx specific fields
	ValidationId []byte `protobuf:"bytes,6,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"` // 32 bytes
	SubnetAuth   []byte `protobuf:"bytes,7,opt,name=subnet_auth,json=subnetAuth,proto3" json:"subnet_auth,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedTx  []byte `protobuf:"bytes,8,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableL1ValidatorTxRequest) Reset() {
	*x = DisableL1ValidatorTxRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableL1ValidatorTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableL1ValidatorTxRequest) ProtoMessage() {}

func (x *DisableL1ValidatorTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableL1ValidatorTxRequest.ProtoReflect.Descriptor instead.
func (*DisableL1ValidatorTxRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{14}
}

func (x *DisableL1ValidatorTxRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *DisableL1ValidatorTxRequest) GetBlockchainId() []byte {
	if x != nil {
		return x.BlockchainId
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetOutputs() []*TransferableOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetInputs() []*TransferableInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetValidationId() []byte {
	if x != nil {
		return x.ValidationId
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetSubnetAuth() []byte {
	if x != nil {
		return x.SubnetAuth
	}
	return nil
}

func (x *DisableL1ValidatorTxRequest) GetSerializedTx() []byte {
	if x != nil {
		return x.SerializedTx
	}
	return nil
}

// Warp UnsignedMessage serialization
type WarpUnsignedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     uint32                 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	SourceChainId []byte                 `protobuf:"bytes,2,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"` // 32 bytes
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedMsg []byte `protobuf:"bytes,4,opt,name=serialized_msg,json=serializedMsg,proto3" json:"serialized_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpUnsignedMessageRequest) Reset() {
	*x = WarpUnsignedMessageRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpUnsignedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpUnsignedMessageRequest) ProtoMessage() {}

func (x *WarpUnsignedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpUnsignedMessageRequest.ProtoReflect.Descriptor instead.
func (*WarpUnsignedMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{15}
}

func (x *WarpUnsignedMessageRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *WarpUnsignedMessageRequest) GetSourceChainId() []byte {
	if x != nil {
		return x.SourceChainId
	}
	return nil
}

func (x *WarpUnsignedMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WarpUnsignedMessageRequest) GetSerializedMsg() []byte {
	if x != nil {
		return x.SerializedMsg
	}
	return nil
}

// Warp Message (with aggregated BLS signature)
type WarpMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UnsignedMessage []byte                 `protobuf:"bytes,1,opt,name=unsigned_message,json=unsignedMessage,proto3" json:"unsigned_message,omitempty"` // Serialized UnsignedMessage
	SignatureBitSet []byte                 `protobuf:"bytes,2,opt,name=signature_bit_set,json=signatureBitSet,proto3" json:"signature_bit_set,omitempty"`
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Aggregated BLS signature (96 bytes)
	// Rust-serialized bytes for comparison
	SerializedMsg []byte `protobuf:"bytes,4,opt,name=serialized_msg,json=serializedMsg,proto3" json:"serialized_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpMessageRequest) Reset() {
	*x = WarpMessageRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpMessageRequest) ProtoMessage() {}

func (x *WarpMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpMessageRequest.ProtoReflect.Descriptor instead.
func (*WarpMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{16}
}

func (x *WarpMessageRequest) GetUnsignedMessage() []byte {
	if x != nil {
		return x.UnsignedMessage
	}
	return nil
}

func (x *WarpMessageRequest) GetSignatureBitSet() []byte {
	if x != nil {
		return x.SignatureBitSet
	}
	return nil
}

func (x *WarpMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *WarpMessageRequest) GetSerializedMsg() []byte {
	if x != nil {
		return x.SerializedMsg
	}
	return nil
}

// Helper type for including warp message in transactions
type WarpMessageBytes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UnsignedMessage []byte                 `protobuf:"bytes,1,opt,name=unsigned_message,json=unsignedMessage,proto3" json:"unsigned_message,omitempty"`
	SignatureBitSet []byte                 `protobuf:"bytes,2,opt,name=signature_bit_set,json=signatureBitSet,proto3" json:"signature_bit_set,omitempty"`
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WarpMessageBytes) Reset() {
	*x = WarpMessageBytes{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpMessageBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpMessageBytes) ProtoMessage() {}

func (x *WarpMessageBytes) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpMessageBytes.ProtoReflect.Descriptor instead.
func (*WarpMessageBytes) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{17}
}

func (x *WarpMessageBytes) GetUnsignedMessage() []byte {
	if x != nil {
		return x.UnsignedMessage
	}
	return nil
}

func (x *WarpMessageBytes) GetSignatureBitSet() []byte {
	if x != nil {
		return x.SignatureBitSet
	}
	return nil
}

func (x *WarpMessageBytes) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// RegisterL1ValidatorMessage payload (Type ID: 1)
type RegisterL1ValidatorPayloadRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SubnetId              []byte                 `protobuf:"bytes,1,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	NodeId                []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                     // 20 bytes
	BlsPublicKey          []byte                 `protobuf:"bytes,3,opt,name=bls_public_key,json=blsPublicKey,proto3" json:"bls_public_key,omitempty"` // 48 bytes
	Expiry                uint64                 `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	RemainingBalanceOwner *PChainOwner           `protobuf:"bytes,5,opt,name=remaining_balance_owner,json=remainingBalanceOwner,proto3" json:"remaining_balance_owner,omitempty"`
	DisableOwner          *PChainOwner           `protobuf:"bytes,6,opt,name=disable_owner,json=disableOwner,proto3" json:"disable_owner,omitempty"`
	Weight                uint64                 `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedPayload []byte `protobuf:"bytes,8,opt,name=serialized_payload,json=serializedPayload,proto3" json:"serialized_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterL1ValidatorPayloadRequest) Reset() {
	*x = RegisterL1ValidatorPayloadRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterL1ValidatorPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterL1ValidatorPayloadRequest) ProtoMessage() {}

func (x *RegisterL1ValidatorPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterL1ValidatorPayloadRequest.ProtoReflect.Descriptor instead.
func (*RegisterL1ValidatorPayloadRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterL1ValidatorPayloadRequest) GetSubnetId() []byte {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadRequest) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadRequest) GetBlsPublicKey() []byte {
	if x != nil {
		return x.BlsPublicKey
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadRequest) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *RegisterL1ValidatorPayloadRequest) GetRemainingBalanceOwner() *PChainOwner {
	if x != nil {
		return x.RemainingBalanceOwner
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadRequest) GetDisableOwner() *PChainOwner {
	if x != nil {
		return x.DisableOwner
	}
	return nil
}

func (x *RegisterL1ValidatorPayloadRequest) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RegisterL1ValidatorPayloadRequest) GetSerializedPayload() []byte {
	if x != nil {
		return x.SerializedPayload
	}
	return nil
}

// L1ValidatorWeightMessage payload (Type ID: 3)
type L1ValidatorWeightPayloadRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ValidationId []byte                 `protobuf:"bytes,1,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"` // 32 bytes
	Nonce        uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Weight       uint64                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Rust-serialized bytes for comparison
	SerializedPayload []byte `protobuf:"bytes,4,opt,name=serialized_payload,json=serializedPayload,proto3" json:"serialized_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *L1ValidatorWeightPayloadRequest) Reset() {
	*x = L1ValidatorWeightPayloadRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1ValidatorWeightPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1ValidatorWeightPayloadRequest) ProtoMessage() {}

func (x *L1ValidatorWeightPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1ValidatorWeightPayloadRequest.ProtoReflect.Descriptor instead.
func (*L1ValidatorWeightPayloadRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{19}
}

func (x *L1ValidatorWeightPayloadRequest) GetValidationId() []byte {
	if x != nil {
		return x.ValidationId
	}
	return nil
}

func (x *L1ValidatorWeightPayloadRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *L1ValidatorWeightPayloadRequest) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *L1ValidatorWeightPayloadRequest) GetSerializedPayload() []byte {
	if x != nil {
		return x.SerializedPayload
	}
	return nil
}

// SubnetToL1ConversionMessage payload (Type ID: 0)
type SubnetToL1ConversionPayloadRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SubnetId []byte                 `protobuf:"bytes,1,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"` // 32 bytes
	// Rust-serialized bytes for comparison
	SerializedPayload []byte `protobuf:"bytes,2,opt,name=serialized_payload,json=serializedPayload,proto3" json:"serialized_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubnetToL1ConversionPayloadRequest) Reset() {
	*x = SubnetToL1ConversionPayloadRequest{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetToL1ConversionPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetToL1ConversionPayloadRequest) ProtoMessage() {}

func (x *SubnetToL1ConversionPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetToL1ConversionPayloadRequest.ProtoReflect.Descriptor instead.
func (*SubnetToL1ConversionPayloadRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{20}
}

func (x *SubnetToL1ConversionPayloadRequest) GetSubnetId() []byte {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *SubnetToL1ConversionPayloadRequest) GetSerializedPayload() []byte {
	if x != nil {
		return x.SerializedPayload
	}
	return nil
}

// P-Chain owner for validator management
type PChainOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     uint32                 `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Addresses     [][]byte               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"` // Each address is 20 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PChainOwner) Reset() {
	*x = PChainOwner{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PChainOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PChainOwner) ProtoMessage() {}

func (x *PChainOwner) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PChainOwner.ProtoReflect.Descriptor instead.
func (*PChainOwner) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{21}
}

func (x *PChainOwner) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *PChainOwner) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Initial L1 validator for subnet conversion
type InitialL1Validator struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                     // 20 bytes
	BlsPublicKey          []byte                 `protobuf:"bytes,2,opt,name=bls_public_key,json=blsPublicKey,proto3" json:"bls_public_key,omitempty"` // 48 bytes
	Weight                uint64                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	RemainingBalanceOwner *PChainOwner           `protobuf:"bytes,4,opt,name=remaining_balance_owner,json=remainingBalanceOwner,proto3" json:"remaining_balance_owner,omitempty"`
	DeactivationOwner     *PChainOwner           `protobuf:"bytes,5,opt,name=deactivation_owner,json=deactivationOwner,proto3" json:"deactivation_owner,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitialL1Validator) Reset() {
	*x = InitialL1Validator{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialL1Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialL1Validator) ProtoMessage() {}

func (x *InitialL1Validator) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialL1Validator.ProtoReflect.Descriptor instead.
func (*InitialL1Validator) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{22}
}

func (x *InitialL1Validator) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *InitialL1Validator) GetBlsPublicKey() []byte {
	if x != nil {
		return x.BlsPublicKey
	}
	return nil
}

func (x *InitialL1Validator) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *InitialL1Validator) GetRemainingBalanceOwner() *PChainOwner {
	if x != nil {
		return x.RemainingBalanceOwner
	}
	return nil
}

func (x *InitialL1Validator) GetDeactivationOwner() *PChainOwner {
	if x != nil {
		return x.DeactivationOwner
	}
	return nil
}

// UTXO output reference
type TransferableOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       []byte                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // 32 bytes
	Output        *OutputPayload         `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferableOutput) Reset() {
	*x = TransferableOutput{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferableOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferableOutput) ProtoMessage() {}

func (x *TransferableOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferableOutput.ProtoReflect.Descriptor instead.
func (*TransferableOutput) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{23}
}

func (x *TransferableOutput) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *TransferableOutput) GetOutput() *OutputPayload {
	if x != nil {
		return x.Output
	}
	return nil
}

// UTXO input reference
type TransferableInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          []byte                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // 32 bytes
	OutputIndex   uint32                 `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	AssetId       []byte                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // 32 bytes
	Input         *InputPayload          `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferableInput) Reset() {
	*x = TransferableInput{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferableInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferableInput) ProtoMessage() {}

func (x *TransferableInput) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferableInput.ProtoReflect.Descriptor instead.
func (*TransferableInput) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{24}
}

func (x *TransferableInput) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *TransferableInput) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *TransferableInput) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *TransferableInput) GetInput() *InputPayload {
	if x != nil {
		return x.Input
	}
	return nil
}

// Output payload (SECP256K1 transfer output)
type OutputPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Locktime      uint64                 `protobuf:"varint,2,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Threshold     uint32                 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Addresses     [][]byte               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"` // Each address is 20 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputPayload) Reset() {
	*x = OutputPayload{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPayload) ProtoMessage() {}

func (x *OutputPayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPayload.ProtoReflect.Descriptor instead.
func (*OutputPayload) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{25}
}

func (x *OutputPayload) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OutputPayload) GetLocktime() uint64 {
	if x != nil {
		return x.Locktime
	}
	return 0
}

func (x *OutputPayload) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *OutputPayload) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Input payload (SECP256K1 transfer input)
type InputPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	SigIndices    []uint32               `protobuf:"varint,2,rep,packed,name=sig_indices,json=sigIndices,proto3" json:"sig_indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputPayload) Reset() {
	*x = InputPayload{}
	mi := &file_rpcpb_l1tx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputPayload) ProtoMessage() {}

func (x *InputPayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_l1tx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputPayload.ProtoReflect.Descriptor instead.
func (*InputPayload) Descriptor() ([]byte, []int) {
	return file_rpcpb_l1tx_proto_rawDescGZIP(), []int{26}
}

func (x *InputPayload) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InputPayload) GetSigIndices() []uint32 {
	if x != nil {
		return x.SigIndices
	}
	return nil
}

var File_rpcpb_l1tx_proto protoreflect.FileDescriptor

const file_rpcpb_l1tx_proto_rawDesc = "" +
	"\n" +
	"\x10rpcpb/l1tx.proto\x12\x05rpcpb\"\x99\x01\n" +
	"\x1bConvertSubnetToL1TxResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x9b\x01\n" +
	"\x1dRegisterL1ValidatorTxResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x9c\x01\n" +
	"\x1eSetL1ValidatorWeightTxResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xa2\x01\n" +
	"$IncreaseL1ValidatorBalanceTxResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x1cDisableL1ValidatorTxResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x99\x01\n" +
	"\x1bWarpUnsignedMessageResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x13WarpMessageResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xa0\x01\n" +
	"\"RegisterL1ValidatorPayloadResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x9e\x01\n" +
	" L1ValidatorWeightPayloadResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xa1\x01\n" +
	"#SubnetToL1ConversionPayloadResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x1f\n" +
	"\vcomputed_id\x18\x02 \x01(\fR\n" +
	"computedId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xae\x03\n" +
	"\x1aConvertSubnetToL1TxRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12#\n" +
	"\rblockchain_id\x18\x02 \x01(\fR\fblockchainId\x123\n" +
	"\aoutputs\x18\x03 \x03(\v2\x19.rpcpb.TransferableOutputR\aoutputs\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.rpcpb.TransferableInputR\x06inputs\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\fR\x04memo\x12\x1b\n" +
	"\tsubnet_id\x18\x06 \x01(\fR\bsubnetId\x12\x19\n" +
	"\bchain_id\x18\a \x01(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\b \x01(\fR\aaddress\x129\n" +
	"\n" +
	"validators\x18\t \x03(\v2\x19.rpcpb.InitialL1ValidatorR\n" +
	"validators\x12\x1f\n" +
	"\vsubnet_auth\x18\n" +
	" \x01(\fR\n" +
	"subnetAuth\x12#\n" +
	"\rserialized_tx\x18\v \x01(\fR\fserializedTx\"\x8f\x03\n" +
	"\x1cRegisterL1ValidatorTxRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12#\n" +
	"\rblockchain_id\x18\x02 \x01(\fR\fblockchainId\x123\n" +
	"\aoutputs\x18\x03 \x03(\v2\x19.rpcpb.TransferableOutputR\aoutputs\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.rpcpb.TransferableInputR\x06inputs\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\fR\x04memo\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x04R\abalance\x125\n" +
	"\x17bls_proof_of_possession\x18\a \x01(\fR\x14blsProofOfPossession\x12:\n" +
	"\fwarp_message\x18\b \x01(\v2\x17.rpcpb.WarpMessageBytesR\vwarpMessage\x12#\n" +
	"\rserialized_tx\x18\t \x01(\fR\fserializedTx\"\xbf\x02\n" +
	"\x1dSetL1ValidatorWeightTxRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12#\n" +
	"\rblockchain_id\x18\x02 \x01(\fR\fblockchainId\x123\n" +
	"\aoutputs\x18\x03 \x03(\v2\x19.rpcpb.TransferableOutputR\aoutputs\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.rpcpb.TransferableInputR\x06inputs\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\fR\x04memo\x12:\n" +
	"\fwarp_message\x18\x06 \x01(\v2\x17.rpcpb.WarpMessageBytesR\vwarpMessage\x12#\n" +
	"\rserialized_tx\x18\a \x01(\fR\fserializedTx\"\xc8\x02\n" +
	"#IncreaseL1ValidatorBalanceTxRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12#\n" +
	"\rblockchain_id\x18\x02 \x01(\fR\fblockchainId\x123\n" +
	"\aoutputs\x18\x03 \x03(\v2\x19.rpcpb.TransferableOutputR\aoutputs\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.rpcpb.TransferableInputR\x06inputs\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\fR\x04memo\x12#\n" +
	"\rvalidation_id\x18\x06 \x01(\fR\fvalidationId\x12\x18\n" +
	"\abalance\x18\a \x01(\x04R\abalance\x12#\n" +
	"\rserialized_tx\x18\b \x01(\fR\fserializedTx\"\xc7\x02\n" +
	"\x1bDisableL1ValidatorTxRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12#\n" +
	"\rblockchain_id\x18\x02 \x01(\fR\fblockchainId\x123\n" +
	"\aoutputs\x18\x03 \x03(\v2\x19.rpcpb.TransferableOutputR\aoutputs\x120\n" +
	"\x06inputs\x18\x04 \x03(\v2\x18.rpcpb.TransferableInputR\x06inputs\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\fR\x04memo\x12#\n" +
	"\rvalidation_id\x18\x06 \x01(\fR\fvalidationId\x12\x1f\n" +
	"\vsubnet_auth\x18\a \x01(\fR\n" +
	"subnetAuth\x12#\n" +
	"\rserialized_tx\x18\b \x01(\fR\fserializedTx\"\xa4\x01\n" +
	"\x1aWarpUnsignedMessageRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12&\n" +
	"\x0fsource_chain_id\x18\x02 \x01(\fR\rsourceChainId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12%\n" +
	"\x0eserialized_msg\x18\x04 \x01(\fR\rserializedMsg\"\xb0\x01\n" +
	"\x12WarpMessageRequest\x12)\n" +
	"\x10unsigned_message\x18\x01 \x01(\fR\x0funsignedMessage\x12*\n" +
	"\x11signature_bit_set\x18\x02 \x01(\fR\x0fsignatureBitSet\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12%\n" +
	"\x0eserialized_msg\x18\x04 \x01(\fR\rserializedMsg\"\x87\x01\n" +
	"\x10WarpMessageBytes\x12)\n" +
	"\x10unsigned_message\x18\x01 \x01(\fR\x0funsignedMessage\x12*\n" +
	"\x11signature_bit_set\x18\x02 \x01(\fR\x0fsignatureBitSet\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xe3\x02\n" +
	"!RegisterL1ValidatorPayloadRequest\x12\x1b\n" +
	"\tsubnet_id\x18\x01 \x01(\fR\bsubnetId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12$\n" +
	"\x0ebls_public_key\x18\x03 \x01(\fR\fblsPublicKey\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\x04R\x06expiry\x12J\n" +
	"\x17remaining_balance_owner\x18\x05 \x01(\v2\x12.rpcpb.PChainOwnerR\x15remainingBalanceOwner\x127\n" +
	"\rdisable_owner\x18\x06 \x01(\v2\x12.rpcpb.PChainOwnerR\fdisableOwner\x12\x16\n" +
	"\x06weight\x18\a \x01(\x04R\x06weight\x12-\n" +
	"\x12serialized_payload\x18\b \x01(\fR\x11serializedPayload\"\xa3\x01\n" +
	"\x1fL1ValidatorWeightPayloadRequest\x12#\n" +
	"\rvalidation_id\x18\x01 \x01(\fR\fvalidationId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x04R\x06weight\x12-\n" +
	"\x12serialized_payload\x18\x04 \x01(\fR\x11serializedPayload\"p\n" +
	"\"SubnetToL1ConversionPayloadRequest\x12\x1b\n" +
	"\tsubnet_id\x18\x01 \x01(\fR\bsubnetId\x12-\n" +
	"\x12serialized_payload\x18\x02 \x01(\fR\x11serializedPayload\"I\n" +
	"\vPChainOwner\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\rR\tthreshold\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\fR\taddresses\"\xfa\x01\n" +
	"\x12InitialL1Validator\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12$\n" +
	"\x0ebls_public_key\x18\x02 \x01(\fR\fblsPublicKey\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x04R\x06weight\x12J\n" +
	"\x17remaining_balance_owner\x18\x04 \x01(\v2\x12.rpcpb.PChainOwnerR\x15remainingBalanceOwner\x12A\n" +
	"\x12deactivation_owner\x18\x05 \x01(\v2\x12.rpcpb.PChainOwnerR\x11deactivationOwner\"]\n" +
	"\x12TransferableOutput\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\x12,\n" +
	"\x06output\x18\x02 \x01(\v2\x14.rpcpb.OutputPayloadR\x06output\"\x91\x01\n" +
	"\x11TransferableInput\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\x12!\n" +
	"\foutput_index\x18\x02 \x01(\rR\voutputIndex\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\fR\aassetId\x12)\n" +
	"\x05input\x18\x04 \x01(\v2\x13.rpcpb.InputPayloadR\x05input\"\x7f\n" +
	"\rOutputPayload\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x1a\n" +
	"\blocktime\x18\x02 \x01(\x04R\blocktime\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\fR\taddresses\"G\n" +
	"\fInputPayload\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x1f\n" +
	"\vsig_indices\x18\x02 \x03(\rR\n" +
	"sigIndices2\x8a\b\n" +
	"\vL1TxService\x12\\\n" +
	"\x13ConvertSubnetToL1Tx\x12!.rpcpb.ConvertSubnetToL1TxRequest\x1a\".rpcpb.ConvertSubnetToL1TxResponse\x12b\n" +
	"\x15RegisterL1ValidatorTx\x12#.rpcpb.RegisterL1ValidatorTxRequest\x1a$.rpcpb.RegisterL1ValidatorTxResponse\x12e\n" +
	"\x16SetL1ValidatorWeightTx\x12$.rpcpb.SetL1ValidatorWeightTxRequest\x1a%.rpcpb.SetL1ValidatorWeightTxResponse\x12w\n" +
	"\x1cIncreaseL1ValidatorBalanceTx\x12*.rpcpb.IncreaseL1ValidatorBalanceTxRequest\x1a+.rpcpb.IncreaseL1ValidatorBalanceTxResponse\x12_\n" +
	"\x14DisableL1ValidatorTx\x12\".rpcpb.DisableL1ValidatorTxRequest\x1a#.rpcpb.DisableL1ValidatorTxResponse\x12\\\n" +
	"\x13WarpUnsignedMessage\x12!.rpcpb.WarpUnsignedMessageRequest\x1a\".rpcpb.WarpUnsignedMessageResponse\x12D\n" +
	"\vWarpMessage\x12\x19.rpcpb.WarpMessageRequest\x1a\x1a.rpcpb.WarpMessageResponse\x12q\n" +
	"\x1aRegisterL1ValidatorPayload\x12(.rpcpb.RegisterL1ValidatorPayloadRequest\x1a).rpcpb.RegisterL1ValidatorPayloadResponse\x12k\n" +
	"\x18L1ValidatorWeightPayload\x12&.rpcpb.L1ValidatorWeightPayloadRequest\x1a'.rpcpb.L1ValidatorWeightPayloadResponse\x12t\n" +
	"\x1bSubnetToL1ConversionPayload\x12).rpcpb.SubnetToL1ConversionPayloadRequest\x1a*.rpcpb.SubnetToL1ConversionPayloadResponseB@Z>github.com/ava-labs/avalanche-rs/avalanchego-conformance;rpcpbb\x06proto3"

var (
	file_rpcpb_l1tx_proto_rawDescOnce sync.Once
	file_rpcpb_l1tx_proto_rawDescData []byte
)

func file_rpcpb_l1tx_proto_rawDescGZIP() []byte {
	file_rpcpb_l1tx_proto_rawDescOnce.Do(func() {
		file_rpcpb_l1tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_l1tx_proto_rawDesc), len(file_rpcpb_l1tx_proto_rawDesc)))
	})
	return file_rpcpb_l1tx_proto_rawDescData
}

var file_rpcpb_l1tx_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_rpcpb_l1tx_proto_goTypes = []any{
	(*ConvertSubnetToL1TxResponse)(nil),          // 0: rpcpb.ConvertSubnetToL1TxResponse
	(*RegisterL1ValidatorTxResponse)(nil),        // 1: rpcpb.RegisterL1ValidatorTxResponse
	(*SetL1ValidatorWeightTxResponse)(nil),       // 2: rpcpb.SetL1ValidatorWeightTxResponse
	(*IncreaseL1ValidatorBalanceTxResponse)(nil), // 3: rpcpb.IncreaseL1ValidatorBalanceTxResponse
	(*DisableL1ValidatorTxResponse)(nil),         // 4: rpcpb.DisableL1ValidatorTxResponse
	(*WarpUnsignedMessageResponse)(nil),          // 5: rpcpb.WarpUnsignedMessageResponse
	(*WarpMessageResponse)(nil),                  // 6: rpcpb.WarpMessageResponse
	(*RegisterL1ValidatorPayloadResponse)(nil),   // 7: rpcpb.RegisterL1ValidatorPayloadResponse
	(*L1ValidatorWeightPayloadResponse)(nil),     // 8: rpcpb.L1ValidatorWeightPayloadResponse
	(*SubnetToL1ConversionPayloadResponse)(nil),  // 9: rpcpb.SubnetToL1ConversionPayloadResponse
	(*ConvertSubnetToL1TxRequest)(nil),           // 10: rpcpb.ConvertSubnetToL1TxRequest
	(*RegisterL1ValidatorTxRequest)(nil),         // 11: rpcpb.RegisterL1ValidatorTxRequest
	(*SetL1ValidatorWeightTxRequest)(nil),        // 12: rpcpb.SetL1ValidatorWeightTxRequest
	(*IncreaseL1ValidatorBalanceTxRequest)(nil),  // 13: rpcpb.IncreaseL1ValidatorBalanceTxRequest
	(*DisableL1ValidatorTxRequest)(nil),          // 14: rpcpb.DisableL1ValidatorTxRequest
	(*WarpUnsignedMessageRequest)(nil),           // 15: rpcpb.WarpUnsignedMessageRequest
	(*WarpMessageRequest)(nil),                   // 16: rpcpb.WarpMessageRequest
	(*WarpMessageBytes)(nil),                     // 17: rpcpb.WarpMessageBytes
	(*RegisterL1ValidatorPayloadRequest)(nil),    // 18: rpcpb.RegisterL1ValidatorPayloadRequest
	(*L1ValidatorWeightPayloadRequest)(nil),      // 19: rpcpb.L1ValidatorWeightPayloadRequest
	(*SubnetToL1ConversionPayloadRequest)(nil),   // 20: rpcpb.SubnetToL1ConversionPayloadRequest
	(*PChainOwner)(nil),                          // 21: rpcpb.PChainOwner
	(*InitialL1Validator)(nil),                   // 22: rpcpb.InitialL1Validator
	(*TransferableOutput)(nil),                   // 23: rpcpb.TransferableOutput
	(*TransferableInput)(nil),                    // 24: rpcpb.TransferableInput
	(*OutputPayload)(nil),                        // 25: rpcpb.OutputPayload
	(*InputPayload)(nil),                         // 26: rpcpb.InputPayload
}
var file_rpcpb_l1tx_proto_depIdxs = []int32{
	23, // 0: rpcpb.ConvertSubnetToL1TxRequest.outputs:type_name -> rpcpb.TransferableOutput
	24, // 1: rpcpb.ConvertSubnetToL1TxRequest.inputs:type_name -> rpcpb.TransferableInput
	22, // 2: rpcpb.ConvertSubnetToL1TxRequest.validators:type_name -> rpcpb.InitialL1Validator
	23, // 3: rpcpb.RegisterL1ValidatorTxRequest.outputs:type_name -> rpcpb.TransferableOutput
	24, // 4: rpcpb.RegisterL1ValidatorTxRequest.inputs:type_name -> rpcpb.TransferableInput
	17, // 5: rpcpb.RegisterL1ValidatorTxRequest.warp_message:type_name -> rpcpb.WarpMessageBytes
	23, // 6: rpcpb.SetL1ValidatorWeightTxRequest.outputs:type_name -> rpcpb.TransferableOutput
	24, // 7: rpcpb.SetL1ValidatorWeightTxRequest.inputs:type_name -> rpcpb.TransferableInput
	17, // 8: rpcpb.SetL1ValidatorWeightTxRequest.warp_message:type_name -> rpcpb.WarpMessageBytes
	23, // 9: rpcpb.IncreaseL1ValidatorBalanceTxRequest.outputs:type_name -> rpcpb.TransferableOutput
	24, // 10: rpcpb.IncreaseL1ValidatorBalanceTxRequest.inputs:type_name -> rpcpb.TransferableInput
	23, // 11: rpcpb.DisableL1ValidatorTxRequest.outputs:type_name -> rpcpb.TransferableOutput
	24, // 12: rpcpb.DisableL1ValidatorTxRequest.inputs:type_name -> rpcpb.TransferableInput
	21, // 13: rpcpb.RegisterL1ValidatorPayloadRequest.remaining_balance_owner:type_name -> rpcpb.PChainOwner
	21, // 14: rpcpb.RegisterL1ValidatorPayloadRequest.disable_owner:type_name -> rpcpb.PChainOwner
	21, // 15: rpcpb.InitialL1Validator.remaining_balance_owner:type_name -> rpcpb.PChainOwner
	21, // 16: rpcpb.InitialL1Validator.deactivation_owner:type_name -> rpcpb.PChainOwner
	25, // 17: rpcpb.TransferableOutput.output:type_name -> rpcpb.OutputPayload
	26, // 18: rpcpb.TransferableInput.input:type_name -> rpcpb.InputPayload
	10, // 19: rpcpb.L1TxService.ConvertSubnetToL1Tx:input_type -> rpcpb.ConvertSubnetToL1TxRequest
	11, // 20: rpcpb.L1TxService.RegisterL1ValidatorTx:input_type -> rpcpb.RegisterL1ValidatorTxRequest
	12, // 21: rpcpb.L1TxService.SetL1ValidatorWeightTx:input_type -> rpcpb.SetL1ValidatorWeightTxRequest
	13, // 22: rpcpb.L1TxService.IncreaseL1ValidatorBalanceTx:input_type -> rpcpb.IncreaseL1ValidatorBalanceTxRequest
	14, // 23: rpcpb.L1TxService.DisableL1ValidatorTx:input_type -> rpcpb.DisableL1ValidatorTxRequest
	15, // 24: rpcpb.L1TxService.WarpUnsignedMessage:input_type -> rpcpb.WarpUnsignedMessageRequest
	16, // 25: rpcpb.L1TxService.WarpMessage:input_type -> rpcpb.WarpMessageRequest
	18, // 26: rpcpb.L1TxService.RegisterL1ValidatorPayload:input_type -> rpcpb.RegisterL1ValidatorPayloadRequest
	19, // 27: rpcpb.L1TxService.L1ValidatorWeightPayload:input_type -> rpcpb.L1ValidatorWeightPayloadRequest
	20, // 28: rpcpb.L1TxService.SubnetToL1ConversionPayload:input_type -> rpcpb.SubnetToL1ConversionPayloadRequest
	0,  // 29: rpcpb.L1TxService.ConvertSubnetToL1Tx:output_type -> rpcpb.ConvertSubnetToL1TxResponse
	1,  // 30: rpcpb.L1TxService.RegisterL1ValidatorTx:output_type -> rpcpb.RegisterL1ValidatorTxResponse
	2,  // 31: rpcpb.L1TxService.SetL1ValidatorWeightTx:output_type -> rpcpb.SetL1ValidatorWeightTxResponse
	3,  // 32: rpcpb.L1TxService.IncreaseL1ValidatorBalanceTx:output_type -> rpcpb.IncreaseL1ValidatorBalanceTxResponse
	4,  // 33: rpcpb.L1TxService.DisableL1ValidatorTx:output_type -> rpcpb.DisableL1ValidatorTxResponse
	5,  // 34: rpcpb.L1TxService.WarpUnsignedMessage:output_type -> rpcpb.WarpUnsignedMessageResponse
	6,  // 35: rpcpb.L1TxService.WarpMessage:output_type -> rpcpb.WarpMessageResponse
	7,  // 36: rpcpb.L1TxService.RegisterL1ValidatorPayload:output_type -> rpcpb.RegisterL1ValidatorPayloadResponse
	8,  // 37: rpcpb.L1TxService.L1ValidatorWeightPayload:output_type -> rpcpb.L1ValidatorWeightPayloadResponse
	9,  // 38: rpcpb.L1TxService.SubnetToL1ConversionPayload:output_type -> rpcpb.SubnetToL1ConversionPayloadResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_rpcpb_l1tx_proto_init() }
func file_rpcpb_l1tx_proto_init() {
	if File_rpcpb_l1tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_l1tx_proto_rawDesc), len(file_rpcpb_l1tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_l1tx_proto_goTypes,
		DependencyIndexes: file_rpcpb_l1tx_proto_depIdxs,
		MessageInfos:      file_rpcpb_l1tx_proto_msgTypes,
	}.Build()
	File_rpcpb_l1tx_proto = out.File
	file_rpcpb_l1tx_proto_goTypes = nil
	file_rpcpb_l1tx_proto_depIdxs = nil
}
