// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: rpcpb/l1tx.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	L1TxService_ConvertSubnetToL1Tx_FullMethodName          = "/rpcpb.L1TxService/ConvertSubnetToL1Tx"
	L1TxService_RegisterL1ValidatorTx_FullMethodName        = "/rpcpb.L1TxService/RegisterL1ValidatorTx"
	L1TxService_SetL1ValidatorWeightTx_FullMethodName       = "/rpcpb.L1TxService/SetL1ValidatorWeightTx"
	L1TxService_IncreaseL1ValidatorBalanceTx_FullMethodName = "/rpcpb.L1TxService/IncreaseL1ValidatorBalanceTx"
	L1TxService_DisableL1ValidatorTx_FullMethodName         = "/rpcpb.L1TxService/DisableL1ValidatorTx"
	L1TxService_WarpUnsignedMessage_FullMethodName          = "/rpcpb.L1TxService/WarpUnsignedMessage"
	L1TxService_WarpMessage_FullMethodName                  = "/rpcpb.L1TxService/WarpMessage"
	L1TxService_RegisterL1ValidatorPayload_FullMethodName   = "/rpcpb.L1TxService/RegisterL1ValidatorPayload"
	L1TxService_L1ValidatorWeightPayload_FullMethodName     = "/rpcpb.L1TxService/L1ValidatorWeightPayload"
	L1TxService_SubnetToL1ConversionPayload_FullMethodName  = "/rpcpb.L1TxService/SubnetToL1ConversionPayload"
)

// L1TxServiceClient is the client API for L1TxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// L1TxService provides conformance testing for Granite upgrade transaction types.
// These transactions were introduced in Etna (ACP-77) for L1 validator management.
type L1TxServiceClient interface {
	// Transaction serialization conformance
	ConvertSubnetToL1Tx(ctx context.Context, in *ConvertSubnetToL1TxRequest, opts ...grpc.CallOption) (*ConvertSubnetToL1TxResponse, error)
	RegisterL1ValidatorTx(ctx context.Context, in *RegisterL1ValidatorTxRequest, opts ...grpc.CallOption) (*RegisterL1ValidatorTxResponse, error)
	SetL1ValidatorWeightTx(ctx context.Context, in *SetL1ValidatorWeightTxRequest, opts ...grpc.CallOption) (*SetL1ValidatorWeightTxResponse, error)
	IncreaseL1ValidatorBalanceTx(ctx context.Context, in *IncreaseL1ValidatorBalanceTxRequest, opts ...grpc.CallOption) (*IncreaseL1ValidatorBalanceTxResponse, error)
	DisableL1ValidatorTx(ctx context.Context, in *DisableL1ValidatorTxRequest, opts ...grpc.CallOption) (*DisableL1ValidatorTxResponse, error)
	// Warp message serialization
	WarpUnsignedMessage(ctx context.Context, in *WarpUnsignedMessageRequest, opts ...grpc.CallOption) (*WarpUnsignedMessageResponse, error)
	WarpMessage(ctx context.Context, in *WarpMessageRequest, opts ...grpc.CallOption) (*WarpMessageResponse, error)
	// Warp payload serialization (RegisterL1ValidatorMessage, L1ValidatorWeightMessage)
	RegisterL1ValidatorPayload(ctx context.Context, in *RegisterL1ValidatorPayloadRequest, opts ...grpc.CallOption) (*RegisterL1ValidatorPayloadResponse, error)
	L1ValidatorWeightPayload(ctx context.Context, in *L1ValidatorWeightPayloadRequest, opts ...grpc.CallOption) (*L1ValidatorWeightPayloadResponse, error)
	SubnetToL1ConversionPayload(ctx context.Context, in *SubnetToL1ConversionPayloadRequest, opts ...grpc.CallOption) (*SubnetToL1ConversionPayloadResponse, error)
}

type l1TxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewL1TxServiceClient(cc grpc.ClientConnInterface) L1TxServiceClient {
	return &l1TxServiceClient{cc}
}

func (c *l1TxServiceClient) ConvertSubnetToL1Tx(ctx context.Context, in *ConvertSubnetToL1TxRequest, opts ...grpc.CallOption) (*ConvertSubnetToL1TxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertSubnetToL1TxResponse)
	err := c.cc.Invoke(ctx, L1TxService_ConvertSubnetToL1Tx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) RegisterL1ValidatorTx(ctx context.Context, in *RegisterL1ValidatorTxRequest, opts ...grpc.CallOption) (*RegisterL1ValidatorTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterL1ValidatorTxResponse)
	err := c.cc.Invoke(ctx, L1TxService_RegisterL1ValidatorTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) SetL1ValidatorWeightTx(ctx context.Context, in *SetL1ValidatorWeightTxRequest, opts ...grpc.CallOption) (*SetL1ValidatorWeightTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetL1ValidatorWeightTxResponse)
	err := c.cc.Invoke(ctx, L1TxService_SetL1ValidatorWeightTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) IncreaseL1ValidatorBalanceTx(ctx context.Context, in *IncreaseL1ValidatorBalanceTxRequest, opts ...grpc.CallOption) (*IncreaseL1ValidatorBalanceTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncreaseL1ValidatorBalanceTxResponse)
	err := c.cc.Invoke(ctx, L1TxService_IncreaseL1ValidatorBalanceTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) DisableL1ValidatorTx(ctx context.Context, in *DisableL1ValidatorTxRequest, opts ...grpc.CallOption) (*DisableL1ValidatorTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableL1ValidatorTxResponse)
	err := c.cc.Invoke(ctx, L1TxService_DisableL1ValidatorTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) WarpUnsignedMessage(ctx context.Context, in *WarpUnsignedMessageRequest, opts ...grpc.CallOption) (*WarpUnsignedMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarpUnsignedMessageResponse)
	err := c.cc.Invoke(ctx, L1TxService_WarpUnsignedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) WarpMessage(ctx context.Context, in *WarpMessageRequest, opts ...grpc.CallOption) (*WarpMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarpMessageResponse)
	err := c.cc.Invoke(ctx, L1TxService_WarpMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) RegisterL1ValidatorPayload(ctx context.Context, in *RegisterL1ValidatorPayloadRequest, opts ...grpc.CallOption) (*RegisterL1ValidatorPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterL1ValidatorPayloadResponse)
	err := c.cc.Invoke(ctx, L1TxService_RegisterL1ValidatorPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) L1ValidatorWeightPayload(ctx context.Context, in *L1ValidatorWeightPayloadRequest, opts ...grpc.CallOption) (*L1ValidatorWeightPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(L1ValidatorWeightPayloadResponse)
	err := c.cc.Invoke(ctx, L1TxService_L1ValidatorWeightPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l1TxServiceClient) SubnetToL1ConversionPayload(ctx context.Context, in *SubnetToL1ConversionPayloadRequest, opts ...grpc.CallOption) (*SubnetToL1ConversionPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetToL1ConversionPayloadResponse)
	err := c.cc.Invoke(ctx, L1TxService_SubnetToL1ConversionPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// L1TxServiceServer is the server API for L1TxService service.
// All implementations must embed UnimplementedL1TxServiceServer
// for forward compatibility.
//
// L1TxService provides conformance testing for Granite upgrade transaction types.
// These transactions were introduced in Etna (ACP-77) for L1 validator management.
type L1TxServiceServer interface {
	// Transaction serialization conformance
	ConvertSubnetToL1Tx(context.Context, *ConvertSubnetToL1TxRequest) (*ConvertSubnetToL1TxResponse, error)
	RegisterL1ValidatorTx(context.Context, *RegisterL1ValidatorTxRequest) (*RegisterL1ValidatorTxResponse, error)
	SetL1ValidatorWeightTx(context.Context, *SetL1ValidatorWeightTxRequest) (*SetL1ValidatorWeightTxResponse, error)
	IncreaseL1ValidatorBalanceTx(context.Context, *IncreaseL1ValidatorBalanceTxRequest) (*IncreaseL1ValidatorBalanceTxResponse, error)
	DisableL1ValidatorTx(context.Context, *DisableL1ValidatorTxRequest) (*DisableL1ValidatorTxResponse, error)
	// Warp message serialization
	WarpUnsignedMessage(context.Context, *WarpUnsignedMessageRequest) (*WarpUnsignedMessageResponse, error)
	WarpMessage(context.Context, *WarpMessageRequest) (*WarpMessageResponse, error)
	// Warp payload serialization (RegisterL1ValidatorMessage, L1ValidatorWeightMessage)
	RegisterL1ValidatorPayload(context.Context, *RegisterL1ValidatorPayloadRequest) (*RegisterL1ValidatorPayloadResponse, error)
	L1ValidatorWeightPayload(context.Context, *L1ValidatorWeightPayloadRequest) (*L1ValidatorWeightPayloadResponse, error)
	SubnetToL1ConversionPayload(context.Context, *SubnetToL1ConversionPayloadRequest) (*SubnetToL1ConversionPayloadResponse, error)
	mustEmbedUnimplementedL1TxServiceServer()
}

// UnimplementedL1TxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedL1TxServiceServer struct{}

func (UnimplementedL1TxServiceServer) ConvertSubnetToL1Tx(context.Context, *ConvertSubnetToL1TxRequest) (*ConvertSubnetToL1TxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertSubnetToL1Tx not implemented")
}
func (UnimplementedL1TxServiceServer) RegisterL1ValidatorTx(context.Context, *RegisterL1ValidatorTxRequest) (*RegisterL1ValidatorTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterL1ValidatorTx not implemented")
}
func (UnimplementedL1TxServiceServer) SetL1ValidatorWeightTx(context.Context, *SetL1ValidatorWeightTxRequest) (*SetL1ValidatorWeightTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetL1ValidatorWeightTx not implemented")
}
func (UnimplementedL1TxServiceServer) IncreaseL1ValidatorBalanceTx(context.Context, *IncreaseL1ValidatorBalanceTxRequest) (*IncreaseL1ValidatorBalanceTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncreaseL1ValidatorBalanceTx not implemented")
}
func (UnimplementedL1TxServiceServer) DisableL1ValidatorTx(context.Context, *DisableL1ValidatorTxRequest) (*DisableL1ValidatorTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableL1ValidatorTx not implemented")
}
func (UnimplementedL1TxServiceServer) WarpUnsignedMessage(context.Context, *WarpUnsignedMessageRequest) (*WarpUnsignedMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WarpUnsignedMessage not implemented")
}
func (UnimplementedL1TxServiceServer) WarpMessage(context.Context, *WarpMessageRequest) (*WarpMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WarpMessage not implemented")
}
func (UnimplementedL1TxServiceServer) RegisterL1ValidatorPayload(context.Context, *RegisterL1ValidatorPayloadRequest) (*RegisterL1ValidatorPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterL1ValidatorPayload not implemented")
}
func (UnimplementedL1TxServiceServer) L1ValidatorWeightPayload(context.Context, *L1ValidatorWeightPayloadRequest) (*L1ValidatorWeightPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method L1ValidatorWeightPayload not implemented")
}
func (UnimplementedL1TxServiceServer) SubnetToL1ConversionPayload(context.Context, *SubnetToL1ConversionPayloadRequest) (*SubnetToL1ConversionPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubnetToL1ConversionPayload not implemented")
}
func (UnimplementedL1TxServiceServer) mustEmbedUnimplementedL1TxServiceServer() {}
func (UnimplementedL1TxServiceServer) testEmbeddedByValue()                     {}

// UnsafeL1TxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to L1TxServiceServer will
// result in compilation errors.
type UnsafeL1TxServiceServer interface {
	mustEmbedUnimplementedL1TxServiceServer()
}

func RegisterL1TxServiceServer(s grpc.ServiceRegistrar, srv L1TxServiceServer) {
	// If the following call panics, it indicates UnimplementedL1TxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&L1TxService_ServiceDesc, srv)
}

func _L1TxService_ConvertSubnetToL1Tx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertSubnetToL1TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).ConvertSubnetToL1Tx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_ConvertSubnetToL1Tx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).ConvertSubnetToL1Tx(ctx, req.(*ConvertSubnetToL1TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_RegisterL1ValidatorTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterL1ValidatorTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).RegisterL1ValidatorTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_RegisterL1ValidatorTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).RegisterL1ValidatorTx(ctx, req.(*RegisterL1ValidatorTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_SetL1ValidatorWeightTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetL1ValidatorWeightTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).SetL1ValidatorWeightTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_SetL1ValidatorWeightTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).SetL1ValidatorWeightTx(ctx, req.(*SetL1ValidatorWeightTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_IncreaseL1ValidatorBalanceTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseL1ValidatorBalanceTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).IncreaseL1ValidatorBalanceTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_IncreaseL1ValidatorBalanceTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).IncreaseL1ValidatorBalanceTx(ctx, req.(*IncreaseL1ValidatorBalanceTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_DisableL1ValidatorTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableL1ValidatorTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).DisableL1ValidatorTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_DisableL1ValidatorTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).DisableL1ValidatorTx(ctx, req.(*DisableL1ValidatorTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_WarpUnsignedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarpUnsignedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).WarpUnsignedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_WarpUnsignedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).WarpUnsignedMessage(ctx, req.(*WarpUnsignedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_WarpMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarpMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).WarpMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_WarpMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).WarpMessage(ctx, req.(*WarpMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_RegisterL1ValidatorPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterL1ValidatorPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).RegisterL1ValidatorPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_RegisterL1ValidatorPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).RegisterL1ValidatorPayload(ctx, req.(*RegisterL1ValidatorPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_L1ValidatorWeightPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(L1ValidatorWeightPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).L1ValidatorWeightPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_L1ValidatorWeightPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).L1ValidatorWeightPayload(ctx, req.(*L1ValidatorWeightPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L1TxService_SubnetToL1ConversionPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetToL1ConversionPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L1TxServiceServer).SubnetToL1ConversionPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L1TxService_SubnetToL1ConversionPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L1TxServiceServer).SubnetToL1ConversionPayload(ctx, req.(*SubnetToL1ConversionPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// L1TxService_ServiceDesc is the grpc.ServiceDesc for L1TxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var L1TxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.L1TxService",
	HandlerType: (*L1TxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertSubnetToL1Tx",
			Handler:    _L1TxService_ConvertSubnetToL1Tx_Handler,
		},
		{
			MethodName: "RegisterL1ValidatorTx",
			Handler:    _L1TxService_RegisterL1ValidatorTx_Handler,
		},
		{
			MethodName: "SetL1ValidatorWeightTx",
			Handler:    _L1TxService_SetL1ValidatorWeightTx_Handler,
		},
		{
			MethodName: "IncreaseL1ValidatorBalanceTx",
			Handler:    _L1TxService_IncreaseL1ValidatorBalanceTx_Handler,
		},
		{
			MethodName: "DisableL1ValidatorTx",
			Handler:    _L1TxService_DisableL1ValidatorTx_Handler,
		},
		{
			MethodName: "WarpUnsignedMessage",
			Handler:    _L1TxService_WarpUnsignedMessage_Handler,
		},
		{
			MethodName: "WarpMessage",
			Handler:    _L1TxService_WarpMessage_Handler,
		},
		{
			MethodName: "RegisterL1ValidatorPayload",
			Handler:    _L1TxService_RegisterL1ValidatorPayload_Handler,
		},
		{
			MethodName: "L1ValidatorWeightPayload",
			Handler:    _L1TxService_L1ValidatorWeightPayload_Handler,
		},
		{
			MethodName: "SubnetToL1ConversionPayload",
			Handler:    _L1TxService_SubnetToL1ConversionPayload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcpb/l1tx.proto",
}
