// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpcpb/packer.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildVertexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodecVersion  uint32                 `protobuf:"varint,1,opt,name=codec_version,json=codecVersion,proto3" json:"codec_version,omitempty"`
	ChainId       []byte                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Epoch         uint32                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ParentIds     [][]byte               `protobuf:"bytes,5,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	Txs           [][]byte               `protobuf:"bytes,6,rep,name=txs,proto3" json:"txs,omitempty"`
	VtxBytes      []byte                 `protobuf:"bytes,7,opt,name=vtx_bytes,json=vtxBytes,proto3" json:"vtx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildVertexRequest) Reset() {
	*x = BuildVertexRequest{}
	mi := &file_rpcpb_packer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildVertexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildVertexRequest) ProtoMessage() {}

func (x *BuildVertexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_packer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildVertexRequest.ProtoReflect.Descriptor instead.
func (*BuildVertexRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_packer_proto_rawDescGZIP(), []int{0}
}

func (x *BuildVertexRequest) GetCodecVersion() uint32 {
	if x != nil {
		return x.CodecVersion
	}
	return 0
}

func (x *BuildVertexRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *BuildVertexRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BuildVertexRequest) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BuildVertexRequest) GetParentIds() [][]byte {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *BuildVertexRequest) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *BuildVertexRequest) GetVtxBytes() []byte {
	if x != nil {
		return x.VtxBytes
	}
	return nil
}

type BuildVertexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBytes []byte                 `protobuf:"bytes,1,opt,name=expected_bytes,json=expectedBytes,proto3" json:"expected_bytes,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildVertexResponse) Reset() {
	*x = BuildVertexResponse{}
	mi := &file_rpcpb_packer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildVertexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildVertexResponse) ProtoMessage() {}

func (x *BuildVertexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_packer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildVertexResponse.ProtoReflect.Descriptor instead.
func (*BuildVertexResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_packer_proto_rawDescGZIP(), []int{1}
}

func (x *BuildVertexResponse) GetExpectedBytes() []byte {
	if x != nil {
		return x.ExpectedBytes
	}
	return nil
}

func (x *BuildVertexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildVertexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpcpb_packer_proto protoreflect.FileDescriptor

const file_rpcpb_packer_proto_rawDesc = "" +
	"\n" +
	"\x12rpcpb/packer.proto\x12\x05rpcpb\"\xd0\x01\n" +
	"\x12BuildVertexRequest\x12#\n" +
	"\rcodec_version\x18\x01 \x01(\rR\fcodecVersion\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\fR\achainId\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\rR\x05epoch\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x05 \x03(\fR\tparentIds\x12\x10\n" +
	"\x03txs\x18\x06 \x03(\fR\x03txs\x12\x1b\n" +
	"\tvtx_bytes\x18\a \x01(\fR\bvtxBytes\"p\n" +
	"\x13BuildVertexResponse\x12%\n" +
	"\x0eexpected_bytes\x18\x01 \x01(\fR\rexpectedBytes\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2W\n" +
	"\rPackerService\x12F\n" +
	"\vBuildVertex\x12\x19.rpcpb.BuildVertexRequest\x1a\x1a.rpcpb.BuildVertexResponse\"\x00B@Z>github.com/ava-labs/avalanche-rs/avalanchego-conformance;rpcpbb\x06proto3"

var (
	file_rpcpb_packer_proto_rawDescOnce sync.Once
	file_rpcpb_packer_proto_rawDescData []byte
)

func file_rpcpb_packer_proto_rawDescGZIP() []byte {
	file_rpcpb_packer_proto_rawDescOnce.Do(func() {
		file_rpcpb_packer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_packer_proto_rawDesc), len(file_rpcpb_packer_proto_rawDesc)))
	})
	return file_rpcpb_packer_proto_rawDescData
}

var file_rpcpb_packer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpcpb_packer_proto_goTypes = []any{
	(*BuildVertexRequest)(nil),  // 0: rpcpb.BuildVertexRequest
	(*BuildVertexResponse)(nil), // 1: rpcpb.BuildVertexResponse
}
var file_rpcpb_packer_proto_depIdxs = []int32{
	0, // 0: rpcpb.PackerService.BuildVertex:input_type -> rpcpb.BuildVertexRequest
	1, // 1: rpcpb.PackerService.BuildVertex:output_type -> rpcpb.BuildVertexResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_packer_proto_init() }
func file_rpcpb_packer_proto_init() {
	if File_rpcpb_packer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_packer_proto_rawDesc), len(file_rpcpb_packer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_packer_proto_goTypes,
		DependencyIndexes: file_rpcpb_packer_proto_depIdxs,
		MessageInfos:      file_rpcpb_packer_proto_msgTypes,
	}.Build()
	File_rpcpb_packer_proto = out.File
	file_rpcpb_packer_proto_goTypes = nil
	file_rpcpb_packer_proto_depIdxs = nil
}
