// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpcpb/ping.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingServiceRequest) Reset() {
	*x = PingServiceRequest{}
	mi := &file_rpcpb_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServiceRequest) ProtoMessage() {}

func (x *PingServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServiceRequest.ProtoReflect.Descriptor instead.
func (*PingServiceRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_ping_proto_rawDescGZIP(), []int{0}
}

type PingServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingServiceResponse) Reset() {
	*x = PingServiceResponse{}
	mi := &file_rpcpb_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServiceResponse) ProtoMessage() {}

func (x *PingServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServiceResponse.ProtoReflect.Descriptor instead.
func (*PingServiceResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingServiceResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_rpcpb_ping_proto protoreflect.FileDescriptor

const file_rpcpb_ping_proto_rawDesc = "" +
	"\n" +
	"\x10rpcpb/ping.proto\x12\x05rpcpb\"\x14\n" +
	"\x12PingServiceRequest\"'\n" +
	"\x13PingServiceResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid2U\n" +
	"\vPingService\x12F\n" +
	"\vPingService\x12\x19.rpcpb.PingServiceRequest\x1a\x1a.rpcpb.PingServiceResponse\"\x00B@Z>github.com/ava-labs/avalanche-rs/avalanchego-conformance;rpcpbb\x06proto3"

var (
	file_rpcpb_ping_proto_rawDescOnce sync.Once
	file_rpcpb_ping_proto_rawDescData []byte
)

func file_rpcpb_ping_proto_rawDescGZIP() []byte {
	file_rpcpb_ping_proto_rawDescOnce.Do(func() {
		file_rpcpb_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_ping_proto_rawDesc), len(file_rpcpb_ping_proto_rawDesc)))
	})
	return file_rpcpb_ping_proto_rawDescData
}

var file_rpcpb_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpcpb_ping_proto_goTypes = []any{
	(*PingServiceRequest)(nil),  // 0: rpcpb.PingServiceRequest
	(*PingServiceResponse)(nil), // 1: rpcpb.PingServiceResponse
}
var file_rpcpb_ping_proto_depIdxs = []int32{
	0, // 0: rpcpb.PingService.PingService:input_type -> rpcpb.PingServiceRequest
	1, // 1: rpcpb.PingService.PingService:output_type -> rpcpb.PingServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_ping_proto_init() }
func file_rpcpb_ping_proto_init() {
	if File_rpcpb_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_ping_proto_rawDesc), len(file_rpcpb_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_ping_proto_goTypes,
		DependencyIndexes: file_rpcpb_ping_proto_depIdxs,
		MessageInfos:      file_rpcpb_ping_proto_msgTypes,
	}.Build()
	File_rpcpb_ping_proto = out.File
	file_rpcpb_ping_proto_goTypes = nil
	file_rpcpb_ping_proto_depIdxs = nil
}
